name: colleXpass
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  charts_flutter: ^0.10.0
  fl_chart: ^0.36.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/computer_doctor_man.png
    - images/doctor.jpg
    - images/pharmasist.jpg
    - images/default_user.jpg
    - images/facebook_profile_image.png
    - images/logo.png

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Bold.otf
